### PR TITLE
Design layout

### PR DESCRIPTION
**Pull request by raheebwa**
### Highlights
* Project built-in HTML & CSS
* Three breakpoints implemented, 1024, 780 & 480
* Code linted & Validated using WC3 standards (Both HTML & CSS)

### CODE REVIEW

**Review by wathigo — COMMENTED** [review]
## Hi @raheebwa  and @Tripple-A  :wave:  
I like the effort you guys have put into this project, 
but we need to fix some issues before we give this a :+1: 
### REQUIRED 
**Navigation bar**
* It should contain search icon at the rightmost side of sub-navigation row.
* It contains a TNW logo on the leftmost side which is not rendered on medium and smaller screens.
* On smaller screens navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon).

**Top 3 articles section** 
* It contains a TWN logo at the top left corner of the row. The logo is not rendered on smaller screens and medium screen sizes.
* On smaller versions, all articles take the maximum width and are are aligned in one column.

**Latest news section** 
* Aligns three articles per row for the medium size screens.
* Contain one article per row for in small screen sizes.
*  Each articles has a cover image on the left side and title on the right side of the row on small screen sizes. 

**Microsoft Surface Event section**
* Aligns three articles per row on medium screen size.
* Articles occupies max available width on small screen sizes.

**Latest deals section** 
* Contains three latest deals boxes on medium screens.
* Aligns one deal per row.

**After implementing the changes, submit another request for review** 
_Happy coding :computer:_

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good job :+1: 
You have implemented some requested changes but also missed out on important ones. See my comment below and make the changes so we can merge this project.
- [x] add a search icon to the rightmost part of the navigation bar
- [x] add the TNW icon
- [x] remove the horizontal scroll bar on screen below ```768px```.

### Make those changes and re-submit for another review.

**Comment by ebukaume** [comment]
Hi @Tripple-A and @raheebwa :wave: 

Kudos on your efforts so far. You guys have really come a long way but there are still some required features that are still missing.

Firstly, you seem to have forgotten to implement some of the changes pointed out by @wathigo 
 and @whiz25 in your last reviews.

### Navigation Bar
**Large version**
- [x] It contains a search icon at the rightmost side of the sub-navigation row.

**Medium version changes**
- [x] TWN logo appears at the leftmost part.

### Top 3 articles section
**Large version**
- [ ] It contains TWN logo at the top left corner of the row.

**Medium version changes**
- [ ] TWN logo disappears.

### Categories (Apps, GERA, Tech, etc) section
**Medium version changes**
- [x] It aligns 2 category boxes per row.

Finally, kindly take a closer look at the behaviours at the breakpoint set at `@media (max-device-width: 480px)`. It seems the logo covers the whole page at this breakpoint.

tripple-a-issue

**Kindly submit another code review request after implementing these changes.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
[Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Twitter](https://twitter.com/ebukaume)

**Review by stratospherique — CHANGES_REQUESTED** [review]
> ### Code Review By Ahmed Mahfoudh (TSE)

### Hi team :wave: 

- After checking the live preview using https://raw.githach.com, I found out that your project doesn't contain any signs of responsiveness.
image

  - Link: https://rawcdn.githack.com/Tripple-A/Responsive-Design/2f3ba09d40a10ca70db4fb09c7f213fad15adb7d/index.html
  - Maybe you changed something in your last commits that messed with the project. :pray: Take care of this isssue A$AP.

### When finished, kindly resubmit another code review request :pray:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Hi team :wave: 

- Same issue
image

The page is not responsive. :pray: fix it

### When finished, kindly submit another code review request form :pray:

**Comment by raheebwa** [comment]
Please look at the code. I feel there is a problem on yourside

**Review by Redvanisation — APPROVED** [review]
### Hello team 🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
